export const ActionTypes={
    ADD_PRODUCTS: 'ADD_PRODUCTS',
    // DELETE_PRODUCTS : 'DELETE_PRODUCTS',
    SELECTED_PRODUCTS : 'SELECTED_PRODUCTS',
    INCREASE_PRODUCTS: 'INCREASE_PRODUCTS',
    DECREASE_PRODUCTS: 'DECREASE_PRODUCTS',
    GET_NUMBER_CART:'GET_NUMBER_CART',
    CLEAR_CART:'CLEAR_CART'
}